# Generated by Django 6.1.1 on 2026-09-17 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervo.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_registro', models.CharField(max_length=50)),
                ('disponivel', models.BooleanField(default=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervo.livro')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField()),
                ('data_devolucao_prevista', models.DateField()),
                ('data_devolucao_real', models.DateField(blank=True, null=True)),
                ('exemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervo.exemplar')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervo.membro')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField()),
                ('ativa', models.BooleanField(default=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervo.livro')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervo.membro')),
            ],
        ),
    ]
